datagrid:
    issues-grid:
        source:
            acl_resource: bug_tracker.issue_view
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - priority.name as priorityName
                    - priority.order as priorityOrder
                    - resolution.name as resolutionName
                    - issue.type
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: APBugTrackerBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority}
                        - { join: issue.resolution, alias: resolution}

        columns:
            code:
                label: Code
            summary:
                label: Summary
            type:
                label: Type
            priorityName:
                label: Priority
            resolutionName:
                label: Resolution
            createdAt:
                label: Created
                frontend_type: date
            updatedAt:
                label: Updated
                frontend_type: date

        sorters:
            columns:
                priorityName:
                    data_name: priority.order
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      bug_tracker.issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      bug_tracker.issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      ap_bug_tracker_api_delete_issue
                params:     [ id ]

        actions:
            view:
                type: navigate
                acl_resource: bug_tracker.issue_view
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: bug_tracker.issue_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: bug_tracker.issue_delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %ap.bug_tracker.issue.entity.class%
                data_identifier: issue.id
                acl_resource: bug_tracker.issue_delete
                label: Delete
                icon: trash
        options:
            entity_pagination: true

    dashboard-active-issues-grid:
        source:
            acl_resource: bug_tracker.issue_view
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - priority.name as priorityName
                    - priority.order as priorityOrder
                    - resolution.name as resolutionName
                    - issue.type
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: APBugTrackerBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority}
                        - { join: issue.resolution, alias: resolution}

        columns:
            code:
                label: Code
            summary:
                label: Summary
            type:
                label: Type
            priorityName:
                label: Priority
            resolutionName:
                label: Resolution
            createdAt:
                label: Created
                frontend_type: date
            updatedAt:
                label: Updated
                frontend_type: date
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10