datagrid:
    issues-grid:
#    "f[workflowStepLabel][value][]=2&f[workflowStepLabel][value][]=1&f[workflowStepLabel][value][]=3&f[collaborator][value]=2"
        source:
            acl_resource: bug_tracker.issue_view
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - priority.label as priorityName
                    - resolution.label as resolutionName
                    - workflowStep.label as workflowStepLabel
                    - issue.type
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - assignee.id as assigneeId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - issue.createdAt
                    - issue.updatedAt
                    - >
                        (CASE WHEN (:user MEMBER OF issue.collaborators) THEN
                            true
                        ELSE
                            false
                        END) as userInCollaborators
                from:
                    - { table: APBugTrackerBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority}
                        - { join: issue.resolution, alias: resolution}
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }

            bind_parameters:
                -
                    name: user
                    default: 1
#                        - { join: issue.collaborators, alias: collaborator }
#                group_by: issue.id

        columns:
            code:
                label: ap.bugtracker.issue.code.label
            summary:
                label: ap.bugtracker.issue.summary.label
            type:
                label: ap.bugtracker.issue.type.label
            priorityName:
                label: ap.bugtracker.issue.priority.label
            workflowStepLabel:
                label: ap.bugtracker.issue.status.label
            resolutionName:
                label: ap.bugtracker.issue.resolution.label
            reporterName:
                type: twig
                label: ap.bugtracker.issue.reporter.label
                frontend_type: html
                template: APBugTrackerBundle:Issue:Datagrid/Property/user.html.twig
                context:
                    userIdAlias: reporterId
            assigneeName:
                type: twig
                label: ap.bugtracker.issue.assignee.label
                frontend_type: html
                template: APBugTrackerBundle:Issue:Datagrid/Property/user.html.twig
                context:
                    userIdAlias: assigneeId
            createdAt:
                label: ap.bugtracker.issue.created_at.label
                frontend_type: date
            updatedAt:
                label: ap.bugtracker.issue.updated_at.label
                frontend_type: date

        sorters:
            columns:
                code:
                    data_name: issue.code
                type:
                    data_name: issue.type
                priorityName:
                    data_name: priority.order
                resolutionName:
                    data_name: resolution.order
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                updatedAt:
                    data_name: issue.updatedAt
                createdAt:
                    data_name: issue.createdAt
            default:
                updatedAt: DESC

        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                type:
                    type: string
                    data_name: issue.type
                workflowStepLabel:
                    type: choice
                    data_name: issue.workflowStep
                    options:
                        field_options:
                            multiple: true
                            choices: @ap.bug_tracker.grid.issue_grid_helper->getWorkflowStatusChoices
                priorityName:
                    type: string
                    data_name: priorityName
                resolutionName:
                    type: string
                    data_name: resolutionName
                reporterName:
                    type: string
                    data_name: reporterName
                assigneeName:
                    type: string
                    data_name: assigneeName
                createdAt:
                    type: datetime
                    data_name: issue.createdAt
                updatedAt:
                    type: datetime
                    data_name: issue.updatedAt
                collaborator:
                    data_name: userInCollaborators
                    type: boolean
                    label: ap.bugtracker.datagrid.my_issues
                    options:
                        field_options:
                            choices:
                                # in boolean filter type, 1 = yes, 2 = false
                                1: ap.bugtracker.datagrid.yes
                                2: ap.bugtracker.datagrid.no
        properties:
            id: ~
            view_link:
                type:       url
                route:      bug_tracker.issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      bug_tracker.issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      ap_bug_tracker_api_delete_issue
                params:     [ id ]

        actions:
            view:
                type: navigate
                acl_resource: bug_tracker.issue_view
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: bug_tracker.issue_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: bug_tracker.issue_delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %ap.bug_tracker.issue.entity.class%
                data_identifier: issue.id
                acl_resource: bug_tracker.issue_delete
                label: Delete
                icon: trash
        options:
            entity_pagination: true

    dashboard-active-issues-grid:
        extends: issues-grid
        filters:
            default:
                collaborator:
                    value: 1

        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10