datagrid:
    issues-grid:
        source:
            acl_resource: bug_tracker.issue_view
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - priority.name as priorityName #todo priority and resolution name
                    - resolution.name as resolutionName
                    - workflowStep.label as workflowStepLabel
                    - issue.type
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - assignee.id as assigneeId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: APBugTrackerBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority}
                        - { join: issue.resolution, alias: resolution}
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.collaborators, alias: collaborator } #todo

        columns:
            code:
                label: Code
            summary:
                label: Summary
            type:
                label: Type
            priorityName:
                label: Priority
            workflowStepLabel:
                label: Status
            resolutionName:
                label: Resolution
            reporterName:
                type: twig
                label: Reporter
                frontend_type: html
                template: APBugTrackerBundle:Issue:Datagrid/Property/user.html.twig
                context:
                    userIdAlias: reporterId
            assigneeName:
                type: twig
                label: Assignee
                frontend_type: html
                template: APBugTrackerBundle:Issue:Datagrid/Property/user.html.twig
                context:
                    userIdAlias: assigneeId
            createdAt:
                label: Created
                frontend_type: date
            updatedAt:
                label: Updated
                frontend_type: date

        sorters:
            columns:
                code:
                    data_name: issue.code
                type:
                    data_name: issue.type
                priorityName:
                    data_name: priority.order
                resolutionName:
                    data_name: resolution.order
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                updatedAt:
                    data_name: issue.updatedAt
                createdAt:
                    data_name: issue.createdAt
            default:
                updatedAt: DESC

        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                type:
                    type: string
                    data_name: issue.type

                workflowStepLabel:
                    type: entity
                    data_name: issue.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: %ap.bug_tracker.issue.entity.class%
                priorityName:
                    type: string
                    data_name: priorityName
                resolutionName:
                    type: string
                    data_name: resolutionName
                reporterName:
                    type: string
                    data_name: reporterName
                assigneeName:
                    type: string
                    data_name: assigneeName
                createdAt:
                    type: datetime
                    data_name: issue.createdAt
                updatedAt:
                    type: datetime
                    data_name: issue.updatedAt
                collaborator:
                    type: oro_multiple_entity
                    data_name: issue.collaborators
                    options:
                        field_options:
                            class: %oro_user.entity.class%
        properties:
            id: ~
            view_link:
                type:       url
                route:      bug_tracker.issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      bug_tracker.issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      ap_bug_tracker_api_delete_issue
                params:     [ id ]

        actions:
            view:
                type: navigate
                acl_resource: bug_tracker.issue_view
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: bug_tracker.issue_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: bug_tracker.issue_delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %ap.bug_tracker.issue.entity.class%
                data_identifier: issue.id
                acl_resource: bug_tracker.issue_delete
                label: Delete
                icon: trash
        options:
            entity_pagination: true

    dashboard-active-issues-grid:
        source:
            acl_resource: bug_tracker.issue_view
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - priority.name as priorityName
                    - resolution.name as resolutionName
                    - workflowStep.label as workflowStepLabel
                    - issue.type
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - assignee.id as assigneeId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: APBugTrackerBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority}
                        - { join: issue.resolution, alias: resolution}
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.collaborators, alias: collaborator }

        columns:
            code:
                label: Code
            summary:
                label: Summary
            type:
                label: Type
            priorityName:
                label: Priority
            workflowStepLabel:
                label: Status
            resolutionName:
                label: Resolution
            reporterName:
                type: twig
                label: Reporter
                frontend_type: html
                template: APBugTrackerBundle:Issue:Datagrid/Property/user.html.twig
                context:
                    userIdAlias: reporterId
            assigneeName:
                type: twig
                label: Assignee
                frontend_type: html
                template: APBugTrackerBundle:Issue:Datagrid/Property/user.html.twig
                context:
                    userIdAlias: assigneeId
            createdAt:
                label: Created
                frontend_type: date
            updatedAt:
                label: Updated
                frontend_type: date
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10