items:
    ap_bugtracker_add_issue_button:
        template:   APBugTrackerBundle:Issue:addIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)
        acl:        bug_tracker.issue_create
    ap_bugtracker_add_issue_link:
        template:   APBugTrackerBundle:Issue:addIssueLink.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)
        acl:        bug_tracker.issue_create