parameters:
    ap.bug_tracker.manager.issue_api.class:              'Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager'
    ap.bug_tracker.issue_form_handler_api.class:         'AP\Bundle\BugTrackerBundle\Form\Handler\IssueFormHandler'
    ap.bug_tracker.issue_form_handler.class:             'AP\Bundle\BugTrackerBundle\Form\Handler\IssueFormHandler'
    ap.bug_tracker.issue.entity.class:                   'AP\Bundle\BugTrackerBundle\Entity\Issue'
    ap.bug_tracker.subtask_add_permission_checker.class: 'AP\Bundle\BugTrackerBundle\Services\Subtask\CheckAddSubtask'

services:
    ap.bug_tracker.issue_form_handler_api:
        class: %ap.bug_tracker.issue_form_handler_api.class%
        scope: request
        arguments:
            - @ap.bug_tracker.form.issue_api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher
        tags:
            - { name: oro_tag.tag_manager }

    ap.bug_tracker.issue_form_handler:
        class: %ap.bug_tracker.issue_form_handler.class%
        scope: request
        arguments:
            - @ap.bug_tracker.form.issue
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher
        tags:
            - { name: oro_tag.tag_manager }

    ap.bug_tracker.manager.issue_api:
        class: %ap.bug_tracker.manager.issue_api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ap.bug_tracker.issue.entity.class%
            - @doctrine.orm.entity_manager

    ap.bug_tracker.subtask_add_permission_checker:
        class: %ap.bug_tracker.subtask_add_permission_checker.class%