AP\Bundle\BugTrackerBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        type:
            - NotBlank: ~
            #todo
        priority:
            - NotBlank: ~